name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  buildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - run: ./gradlew assemble publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - run: ./gradlew publish --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}

  buildNatives:
    strategy:
      matrix:
        target: [ x86_64, i686, aarch64 ]
    runs-on: windows-latest
    steps:
      # TODO: Fix macOS in future
      - uses: actions/checkout@v4
      - run: rustup target add ${{ matrix.target }}-pc-windows-msvc
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build copyForNative
      - name: Run Cargo
        run: cargo build --release --target ${{ matrix.target }}-pc-windows-msvc
        working-directory: ./native
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.target }}
          path: target/${{ matrix.target }}-pc-windows-msvc/release/quilt-installer.exe
      - run: ./gradlew publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          TARGET: ${{ matrix.target }}
      - run: ./gradlew publish --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
